version: "3.1"

services:
  mongodb:
    image: "bitnami/mongodb:4.4"
    container_name: movie-randomizer-mongodb
    ports:
      - "27017:27017"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_ADVERTISED_HOSTNAME=localhost
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_NAME=replicaset
      - MONGODB_EXTRA_FLAGS=--bind_ip_all
    volumes:
      - volume-mongo:/data/db
  redis:
    image: redis:5.0.6
    container_name: movie-randomizer-redis
    ports:
      - "6379:6379"

volumes:
  volume-mongo:
